Add shadow related extra attribute while adding the user.
pbrezina/sssd-tests-poc pull request #8
Opened 2022-10-11 11:02 UTC by madhuriupadhye

Signed-off-by: Madhuri Upadhye <mupadhye@redhat.com>

2022-10-11 12:40 UTC, pbrezina commented
LGTM for a start, but I think you also need to add shadowAccount object class if any of these are used, don't you? Also please add these attributes to modify and document them.

2022-10-12 09:07 UTC, madhuriupadhye commented
Updated the patch,

Tested locally,

[root@master ~]# ldapsearch -x -b "dc=ldap,dc=test"
# extended LDIF
#
# LDAPv3
# base <dc=ldap,dc=test> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# ldap.test
dn: dc=ldap,dc=test
objectClass: top
objectClass: domain
dc: ldap
description: dc=ldap,dc=test

# users, ldap.test
dn: ou=users,dc=ldap,dc=test
objectClass: organizationalUnit
objectClass: top
ou: users

# tuser, users, ldap.test
dn: cn=tuser,ou=users,dc=ldap,dc=test
objectClass: posixAccount
objectClass: shadowAccount
objectClass: top
cn: tuser
uid: tuser
uidNumber: 10001
gidNumber: 10001
homeDirectory: /home/tuser
shadowMin: 0
shadowLastChange: 19277
userPassword:: e1NIQTI1Nn1MdEJuWm5sZFdLVHlMVkVhWnk4Z3ByQ1cwLzViVnE4NmRFWjRxYU5
 XL1lJPQ==

# search result
search: 2
result: 0 Success

# numResponses: 4
# numEntries: 3

2022-10-12 15:20 UTC, pbrezina commented on lib/multihost/roles/ldap.py
> +        objectClass: list | None = None,
This is unused, please remove it.

2022-10-12 15:20 UTC, pbrezina commented on lib/multihost/roles/ldap.py
> +        objectClass: list | LDAP.Flags | None = None,
I think that objectClass should be hidden to the API and not generally modifiable by the caller. Please, remove the parameter. Also this implementation is wrong since you are adding a list to a list.

One way to handle shadowAccount here would be to remove the class when all shadow attributes are deleted, but I think we can just omit it unless we have any use case for it. If we ever do, we should just provide API to add/remove object class per caller's will instead of trying to be smart.

2022-10-12 15:20 UTC, pbrezina commented on lib/multihost/roles/ldap.py
> +            attrs['objectClass'].append("shadowAccount")
You should check if any of the attributes is not None. You can add a method to BaseObject, e.g.

```python
def _remove_none_from_list(self, l: list[any]) -> list[any]:
    return [x for x in l if x is not None]
```

And then use

```python
if self._remove_none_from_list([shadowMin, shadowMax, shadowWarning, shadowLastChange]):
    attrs['objectClass'].append("shadowAccount")
```

2022-10-13 12:20 UTC, pbrezina requested changes
Hi, we are almost there.

2022-10-13 12:20 UTC, pbrezina commented on lib/multihost/roles/ldap.py
> +            'objectClass': [objectClass],
Please remove it, objectClass is now not defined.

2022-10-13 12:20 UTC, pbrezina commented on lib/multihost/roles/ldap.py
> +        :type l: list[any]
Keep the coding style that is used in other places, remove the space before :type.

2022-10-13 12:20 UTC, pbrezina commented on lib/multihost/roles/ldap.py
> +	Remove none value attributes from list.
This is a generic function and does not need to now about attributes. `Remove all elements that are ``None`` from the list` sounds like a better description.

Separate description and parameters with empty line to improve readability.

2022-10-13 12:20 UTC, pbrezina commented on lib/multihost/roles/ldap.py
> +	:return: List of attribute those not having none value
`New list with all values from the given list that are not ``None`` `

2022-10-14 14:05 UTC, pbrezina requested changes

2022-10-14 14:05 UTC, pbrezina commented on lib/multihost/roles/ldap.py
> +        Remove all elements that are ``None`` from the list
Please, separate param list from description with a blank line.

2022-10-14 14:23 UTC, pbrezina commented
Thank you. One last change, flake8 reports:

```
./lib/multihost/roles/ldap.py:265:38: E741 ambiguous variable name 'l'
./lib/multihost/roles/ldap.py:412:45: E222 multiple spaces after operator
```

2022-10-14 14:24 UTC, pbrezina commented
And please move _remove_none_from_list to BaseObject as it is generic function that can be used everywhere.

2022-10-31 14:24 UTC, pbrezina approved these changes

2022-10-31 14:25 UTC, closed without merging

2022-10-31 14:25 UTC, pbrezina commented
Merged.